### PR TITLE
reduced the number of .gitignore files to 1

### PR DESCRIPTION
**Pull request by mikiTesf**
The .gitignore files had `build/` written in them but I didn't find any folders that go by that name in neither directory (`app/` or `soccerethiopiaapi/`). What do you think?

### CODE REVIEW

**Review by brookmg — CHANGES_REQUESTED** [review]
Add `/build` in the base directory `.gitignore`

**Comment by brookmg** [comment]
You don't see `/build` directory because it was ignored from being staged. It exists locally.

**Comment by mikiTesf** [comment]
It's already there in the root `.gitignore` file. Right under `# Gradle files`

**Comment by brookmg** [comment]
Merged!

**Pull request merged**
